# Generated by Django 6.0.6 on 2026-06-28 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lifeos_app", "0006_populate_domains"),
    ]

    operations = [
        migrations.AddField(
            model_name="appsettings",
            name="priority_weight",
            field=models.FloatField(default=1.5),
        ),
        migrations.AddField(
            model_name="appsettings",
            name="slm_api_key",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="appsettings",
            name="slm_endpoint",
            field=models.CharField(
                default="http://localhost:11434/api/generate", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="appsettings",
            name="slm_provider",
            field=models.CharField(
                choices=[
                    ("Local Ollama", "Local Ollama"),
                    ("Cloud API", "Cloud API"),
                    ("Download Llama-cpp", "Download Llama-cpp"),
                    ("Skip", "Skip"),
                ],
                default="Local Ollama",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="appsettings",
            name="urgency_weight",
            field=models.FloatField(default=2.0),
        ),
        migrations.AddField(
            model_name="executionitem",
            name="urgency",
            field=models.CharField(
                choices=[
                    ("Low", "Low"),
                    ("Normal", "Normal"),
                    ("High", "High"),
                    ("Immediate", "Immediate"),
                ],
                db_index=True,
                default="Normal",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="executionitem",
            name="domain_category",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="workspacecontainer",
            name="domain_category",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.CreateModel(
            name="GoogleCalendarEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.CharField(max_length=255, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("is_blocking", models.BooleanField(default=True)),
                (
                    "calendar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="lifeos_app.googlecalendar",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScheduledTaskAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("score_metric", models.FloatField(default=0.0)),
                (
                    "execution_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduled_allocation",
                        to="lifeos_app.executionitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TimeAvailabilityBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("day_monday", models.BooleanField(default=True)),
                ("day_tuesday", models.BooleanField(default=True)),
                ("day_wednesday", models.BooleanField(default=True)),
                ("day_thursday", models.BooleanField(default=True)),
                ("day_friday", models.BooleanField(default=True)),
                ("day_saturday", models.BooleanField(default=False)),
                ("day_sunday", models.BooleanField(default=False)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "domain",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="lifeos_app.domaincategory",
                    ),
                ),
            ],
        ),
    ]
