# Generated by Django 6.0.6 on 2026-06-28 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "lifeos_app",
            "0007_appsettings_priority_weight_appsettings_slm_api_key_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "color",
                    models.CharField(
                        default="#9966CC", help_text="Hex color code", max_length=7
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="workspacecontainer",
            name="priority",
            field=models.CharField(
                choices=[
                    ("Low", "Low"),
                    ("Medium", "Medium"),
                    ("High", "High"),
                    ("Critical", "Critical"),
                ],
                db_index=True,
                default="Medium",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="workspacecontainer",
            name="urgency",
            field=models.CharField(
                choices=[
                    ("Low", "Low"),
                    ("Normal", "Normal"),
                    ("High", "High"),
                    ("Immediate", "Immediate"),
                ],
                db_index=True,
                default="Normal",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="executionitem",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="execution_items", to="lifeos_app.tag"
            ),
        ),
        migrations.AddField(
            model_name="workspacecontainer",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="containers", to="lifeos_app.tag"
            ),
        ),
    ]
