# Generated by Django 6.0.6 on 2026-06-28 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lifeos_app", "0008_tag_workspacecontainer_priority_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appsettings",
            name="slm_api_key",
        ),
        migrations.RemoveField(
            model_name="executionitem",
            name="domain_category",
        ),
        migrations.RemoveField(
            model_name="workspacecontainer",
            name="domain_category",
        ),
        migrations.AddField(
            model_name="notionintegration",
            name="container",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notion_link",
                to="lifeos_app.workspacecontainer",
            ),
        ),
        migrations.AlterField(
            model_name="executionitem",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("Task", "Task"),
                    ("LearningTask", "LearningTask"),
                    ("LifeActivity", "LifeActivity"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="executionitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("Inbox", "Inbox"),
                    ("Backlog", "Backlog"),
                    ("Planned", "Planned"),
                    ("In Progress", "In Progress"),
                    ("Blocked", "Blocked"),
                    ("Completed", "Completed"),
                ],
                db_index=True,
                default="Inbox",
                max_length=50,
            ),
        ),
    ]
